'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.34014
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'StronglyTypedResourceBuilder generó automáticamente esta clase
'a través de una herramienta como ResGen o Visual Studio.
'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
'con la opción /str o recompile su proyecto de VS.
'''<summary>
'''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class Strings
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CBLauncher.Strings", GetType(Strings).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
    '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a CBLauncher is a software developed by vistaero at 2014 for the people who do not conform with a batch script to start their servers..
    '''</summary>
    Friend Shared ReadOnly Property About() As String
        Get
            Return ResourceManager.GetString("About", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a About CBLauncher.
    '''</summary>
    Friend Shared ReadOnly Property AboutTitle() As String
        Get
            Return ResourceManager.GetString("AboutTitle", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Are you sure?.
    '''</summary>
    Friend Shared ReadOnly Property AreYouSure() As String
        Get
            Return ResourceManager.GetString("AreYouSure", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Latest build already downloaded..
    '''</summary>
    Friend Shared ReadOnly Property CBUpdated1() As String
        Get
            Return ResourceManager.GetString("CBUpdated1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Not download necessary.
    '''</summary>
    Friend Shared ReadOnly Property CBUpdated2() As String
        Get
            Return ResourceManager.GetString("CBUpdated2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Already in favorites with the name .
    '''</summary>
    Friend Shared ReadOnly Property FavoriteExists() As String
        Get
            Return ResourceManager.GetString("FavoriteExists", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Java Files|*.jar.
    '''</summary>
    Friend Shared ReadOnly Property JarFormat() As String
        Get
            Return ResourceManager.GetString("JarFormat", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Java is not installed..
    '''</summary>
    Friend Shared ReadOnly Property JavaNotInstalled1() As String
        Get
            Return ResourceManager.GetString("JavaNotInstalled1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Java not found.
    '''</summary>
    Friend Shared ReadOnly Property JavaNotInstalled2() As String
        Get
            Return ResourceManager.GetString("JavaNotInstalled2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Oups, we are so sorry...
    '''
    '''We think that the last server you launched with this application was not stopped. 
    '''
    '''Probably due to a crash of the launcher. And probably the server is frozen. 
    '''
    '''The only thing which we can do, is killing the process.
    '''
    '''Press No if an important Java application is running, because it would be using the same PID that the server was using.
    '''We recommend restarting your computer soon.
    '''
    '''Process Name and PID: .
    '''</summary>
    Friend Shared ReadOnly Property LastPIDAlert() As String
        Get
            Return ResourceManager.GetString("LastPIDAlert", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a This operation can not be undoned..
    '''</summary>
    Friend Shared ReadOnly Property LdDfProps() As String
        Get
            Return ResourceManager.GetString("LdDfProps", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Shortcut|*.lnk.
    '''</summary>
    Friend Shared ReadOnly Property lnkFormat() As String
        Get
            Return ResourceManager.GetString("lnkFormat", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a File not found..
    '''</summary>
    Friend Shared ReadOnly Property NotFound() As String
        Get
            Return ResourceManager.GetString("NotFound", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a You have not installed Java yet..
    '''</summary>
    Friend Shared ReadOnly Property NotInstalledJavaYet() As String
        Get
            Return ResourceManager.GetString("NotInstalledJavaYet", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Server Properties.
    '''</summary>
    Friend Shared ReadOnly Property PropsTitle() As String
        Get
            Return ResourceManager.GetString("PropsTitle", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Select Jar File.
    '''</summary>
    Friend Shared ReadOnly Property SelectJar() As String
        Get
            Return ResourceManager.GetString("SelectJar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Stop server and close?.
    '''</summary>
    Friend Shared ReadOnly Property ShouldClickStop1() As String
        Get
            Return ResourceManager.GetString("ShouldClickStop1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Where to copy .
    '''</summary>
    Friend Shared ReadOnly Property WhereCopy() As String
        Get
            Return ResourceManager.GetString("WhereCopy", resourceCulture)
        End Get
    End Property
End Class
